spring:
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:database/public-schema.sql
        - classpath:database/archive-schema.sql
      data-locations: classpath:database/dummy-data.sql
