spring:
  application:
    name: ${APP_NAME}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
server:
  servlet:
    context-path: /api
client:
  host: ${CLIENT_HOST}
jwt:
  issuer: ${APP_NAME}
  secret: ${ACCESS_TOKEN_SECRET}
  expiration: 600  # 10 minutes
resend:
  api-key: ${RESEND_API_KEY}
  from: ${RESEND_FROM}
