spring:
  application:
    name: ${APP_NAME}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
server:
  servlet:
    context-path: /api
access-token:
  issuer: ${APP_NAME}
  secret: ${ACCESS_TOKEN_SECRET}
  expiration: 3600
