spring:
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:database/schemas.sql
        - classpath:database/extensions.sql
        - classpath:database/types.sql
        - classpath:database/public/tables.sql
        - classpath:database/public/views.sql
        - classpath:database/public/indexes.sql
        - classpath:database/public/functions.sql
        - classpath:database/public/triggers.sql
        - classpath:database/cron/schedules.sql
        - classpath:database/archive/tables.sql
        - classpath:database/archive/functions.sql
        - classpath:database/archive/triggers.sql
  jpa:
    show-sql: true
